---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: efk
  name: pv-0
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/elasticsearch/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: efk
  name: pv-1
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/elasticsearch/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: efk
  name: pv-2
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/elasticsearch/data"