
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder ".", "/vagrant-ubuntu"
  config.vm.define :ubuntu do |host|
    host.vm.box = "bento/ubuntu-22.04"
    host.vm.hostname = "minikubeCluster"
    host.vm.network :private_network, ip: "192.168.2.10"

    host.vm.disk :disk, size: "20GB", primary: true
    host.vm.provision :shell, path: "bootstrap.sh"

    # Set system settings
    host.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "8192"]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
        vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
    end
  end
end